# aiterm/bootstrap.py
# aiterm: A command-line interface for interacting with AI models.
# Copyright (C) 2025 Dank A. Saurus

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
Handles the first-run setup and ensures the application's file
structure is in place before execution.
"""

import getpass
import platform
import shutil
import sys
from importlib import resources

from . import config
from . import personas as persona_manager
from .logger import log
from .theme_manager import USER_THEMES_DIR


def _prompt_for_api_keys() -> tuple[str, str]:
    """Securely prompts the user for API keys and returns them."""
    print("\n--- API Key Setup ---")
    print("You can get your keys from the following links:")
    print("  - OpenAI: https://platform.openai.com/api-keys")
    print("  - Gemini: https://aistudio.google.com/app/apikey")
    print("Press Enter to skip a key if you do not have one.")
    print("Your input will be hidden for security.")

    try:
        openai_key = getpass.getpass("Enter your OpenAI API key: ")
        gemini_key = getpass.getpass("Enter your Google Gemini API key: ")
        return openai_key.strip(), gemini_key.strip()
    except (KeyboardInterrupt, EOFError):
        print("\n\nAPI key entry cancelled. A blank .env file will be created.")
        return "", ""


def _create_dotenv_file(openai_key: str, gemini_key: str) -> None:
    """Creates the .env file with the provided API keys."""
    env_content = (
        "# This file was generated by aiterm's first-run setup.\n"
        "# This file should not be committed to version control.\n\n"
        f'OPENAI_API_KEY="{openai_key}"\n'
        f'GEMINI_API_KEY="{gemini_key}"\n'
    )
    try:
        config.DOTENV_FILE.write_text(env_content, encoding="utf-8")
        # Set secure file permissions (read/write for owner only) on non-Windows systems.
        if platform.system() != "Windows":
            config.DOTENV_FILE.chmod(0o600)
        log.info("Successfully created .env file at %s", config.DOTENV_FILE)
        print(f"--> API keys saved to: {config.DOTENV_FILE}")
    except OSError as e:
        log.error("Failed to write or set permissions on .env file: %s", e)
        print(
            f"Error: Could not write the .env file to {config.DOTENV_FILE}: {e}",
            file=sys.stderr,
        )
        sys.exit(1)


def _copy_default_themes() -> None:
    """Copies the default packaged themes to the user's theme directory."""
    try:
        packaged_themes_path = resources.files("aiterm.themes")
        for theme_resource in packaged_themes_path.iterdir():
            if theme_resource.name.endswith(".json"):
                dest_path = USER_THEMES_DIR / theme_resource.name
                with resources.as_file(theme_resource) as src_path:
                    shutil.copy2(src_path, dest_path)
        log.info("Copied default themes to %s", USER_THEMES_DIR)
    except (ModuleNotFoundError, FileNotFoundError, OSError) as e:
        log.error("Could not copy default themes: %s", e)
        print(
            f"\nWarning: Could not copy default themes to {USER_THEMES_DIR}: {e}",
            file=sys.stderr,
        )


def _copy_default_docs() -> None:
    """Copies the default documentation to the user's config directory."""
    docs_to_copy = ["assistant_docs.md"]
    all_copied_successfully = True

    for doc_name in docs_to_copy:
        try:
            # Use importlib.resources to reliably find package data
            source_file_traversable = resources.files("aiterm.docs_src").joinpath(
                doc_name
            )
            dest_path = config.DOCS_DIRECTORY / doc_name
            with resources.as_file(source_file_traversable) as source_path:
                shutil.copy2(source_path, dest_path)
        except (FileNotFoundError, OSError) as e:
            all_copied_successfully = False
            log.warning(
                "Could not find or copy documentation source file %s: %s", doc_name, e
            )

    if all_copied_successfully:
        log.info("Copied default documentation to %s", config.DOCS_DIRECTORY)


def _migrate_chat_logs() -> None:
    """
    One-time migration to move user chat logs from the old `logs` directory
    to the new `chatlogs` directory for existing users.
    """
    if config.CHATLOG_DIRECTORY.exists() or not config.LOG_DIRECTORY.exists():
        return  # Migration not needed or already done

    log.info("Performing one-time migration of chat logs.")
    print("--> Migrating existing chat logs to new `chatlogs` directory...")
    config.CHATLOG_DIRECTORY.mkdir(exist_ok=True)
    moved_count = 0
    try:
        for f in config.LOG_DIRECTORY.glob("*.jsonl"):
            if f.name.startswith("chat_") or f.name.startswith("multichat_"):
                shutil.move(str(f), config.CHATLOG_DIRECTORY / f.name)
                moved_count += 1
        if moved_count > 0:
            log.info("Successfully migrated %d chat logs.", moved_count)
            print(f"--> Migrated {moved_count} log files successfully.")
    except (OSError, shutil.Error) as e:
        log.error("Failed during chat log migration: %s", e)
        print(f"Error during chat log migration: {e}", file=sys.stderr)


def _perform_first_run_setup() -> None:
    """Guides the user through the initial setup process."""
    print("--- Welcome to aiterm! ---")
    print("This appears to be your first time running the application.")
    print("To get started, we need to create a few directories.")

    required_dirs = [
        config.CONFIG_DIR,
        config.DATA_DIR,
        config.LOG_DIRECTORY,
        config.CHATLOG_DIRECTORY,
        config.IMAGE_DIRECTORY,
        config.SESSIONS_DIRECTORY,
        config.PERSONAS_DIRECTORY,
        config.DOCS_DIRECTORY,
        USER_THEMES_DIR,
    ]

    print("\nThe following directories will be created:")
    for path in required_dirs:
        print(f"  - {path}")

    try:
        confirm = (
            input("\nDo you want to proceed with the setup? (Y/n): ").lower().strip()
        )
        if confirm not in ["", "y", "yes"]:
            print("Setup aborted by user. Exiting.")
            sys.exit(0)

        print("\n--> Creating directories...")
        for path in required_dirs:
            path.mkdir(parents=True, exist_ok=True)
            log.info("Ensured directory exists: %s", path)
        print("--> Directories created successfully.")

        openai_key, gemini_key = _prompt_for_api_keys()
        _create_dotenv_file(openai_key, gemini_key)

        print("\n--> Creating default 'aiterm_assistant' persona...")
        persona_manager.create_default_persona_if_missing()
        print("--> Default persona created successfully.")

        print("\n--> Copying default themes...")
        _copy_default_themes()
        print("--> Default themes copied successfully.")

        print("\n--> Copying default assistant documentation...")
        _copy_default_docs()
        print("--> Default documentation copied successfully.")

        print("\n--- Setup Complete! ---")
        print(
            "You can now start using aiterm. For a list of commands, run `aiterm chat` and type `/help`."
        )

    except (KeyboardInterrupt, EOFError):
        print("\n\nSetup aborted by user. Exiting.")
        sys.exit(0)
    except OSError as e:
        log.critical(
            "Failed to create necessary directories during first-run setup: %s", e
        )
        print(
            f"\nError: A critical error occurred while creating directories: {e}",
            file=sys.stderr,
        )
        print(
            "Please check your file system permissions and try again.", file=sys.stderr
        )
        sys.exit(1)


def ensure_project_structure() -> None:
    """
    Ensures all necessary directories and default files exist.
    Triggers a guided first-run setup if the main config directory is missing.
    """
    if not config.CONFIG_DIR.exists():
        _perform_first_run_setup()
    else:
        # This is not a first run, but we should still ensure everything is in place.
        required_dirs = [
            config.CONFIG_DIR,
            config.DATA_DIR,
            config.LOG_DIRECTORY,
            config.CHATLOG_DIRECTORY,
            config.IMAGE_DIRECTORY,
            config.SESSIONS_DIRECTORY,
            config.PERSONAS_DIRECTORY,
            config.DOCS_DIRECTORY,
            USER_THEMES_DIR,
        ]
        try:
            for path in required_dirs:
                if not path.exists():
                    log.info("Directory %s not found, creating it.", path)
                    path.mkdir(parents=True, exist_ok=True)

            _migrate_chat_logs()
            persona_manager.create_default_persona_if_missing()

            # Copy docs if the user's docs dir is empty
            if not any(config.DOCS_DIRECTORY.iterdir()):
                log.info("User docs directory is empty. Copying defaults.")
                _copy_default_docs()

            # Copy themes if the user's theme dir is empty
            if not any(USER_THEMES_DIR.iterdir()):
                log.info("User themes directory is empty. Copying defaults.")
                _copy_default_themes()

            if not config.DOTENV_FILE.exists():
                log.warning(".env file not found. Creating an empty one.")
                _create_dotenv_file("", "")

        except OSError as e:
            log.critical("Failed to verify or create project structure: %s", e)
            print(
                f"Error: Could not create a necessary file or directory: {e}",
                file=sys.stderr,
            )
            print("Please check your file system permissions.", file=sys.stderr)
            sys.exit(1)
